# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pixClone_pb2 as pixClone__pb2


class pixCloneStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Disconnect = channel.unary_unary(
        '/pixClone/Disconnect',
        request_serializer=pixClone__pb2.Nothing.SerializeToString,
        response_deserializer=pixClone__pb2.Nothing.FromString,
        )
    self.InfoRequest = channel.unary_unary(
        '/pixClone/InfoRequest',
        request_serializer=pixClone__pb2.Nothing.SerializeToString,
        response_deserializer=pixClone__pb2.Info.FromString,
        )
    self.UpdateRequest = channel.unary_stream(
        '/pixClone/UpdateRequest',
        request_serializer=pixClone__pb2.Nothing.SerializeToString,
        response_deserializer=pixClone__pb2.Pixel.FromString,
        )
    self.modPixels = channel.unary_unary(
        '/pixClone/modPixels',
        request_serializer=pixClone__pb2.Pixel.SerializeToString,
        response_deserializer=pixClone__pb2.Nothing.FromString,
        )


class pixCloneServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Disconnect(self, request, context):
    """Pedido de desconexão
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InfoRequest(self, request, context):
    """Pedido de informação
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateRequest(self, request, context):
    """Pedido da malha de pixels
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def modPixels(self, request, context):
    """Modificação da malha de pixels
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_pixCloneServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Disconnect': grpc.unary_unary_rpc_method_handler(
          servicer.Disconnect,
          request_deserializer=pixClone__pb2.Nothing.FromString,
          response_serializer=pixClone__pb2.Nothing.SerializeToString,
      ),
      'InfoRequest': grpc.unary_unary_rpc_method_handler(
          servicer.InfoRequest,
          request_deserializer=pixClone__pb2.Nothing.FromString,
          response_serializer=pixClone__pb2.Info.SerializeToString,
      ),
      'UpdateRequest': grpc.unary_stream_rpc_method_handler(
          servicer.UpdateRequest,
          request_deserializer=pixClone__pb2.Nothing.FromString,
          response_serializer=pixClone__pb2.Pixel.SerializeToString,
      ),
      'modPixels': grpc.unary_unary_rpc_method_handler(
          servicer.modPixels,
          request_deserializer=pixClone__pb2.Pixel.FromString,
          response_serializer=pixClone__pb2.Nothing.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pixClone', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
